### PR TITLE
Fix donation amounts to match main website

### LINKED ISSUE #79: Update "support the daily" dropdown amounts
image

We should update the dropdown amounts to match those at https://stanforddaily.com/.

### PR DESCRIPTION
**Pull request by ufxela**
## Reasons for making this change

Match donation amounts that the main website has.

## Related tickets

Fixes #79 

## Screenshots

Screen Shot 2020-05-12 at 1 37 04 PM

### CODE REVIEW

File: src/pages/Header.jsx [hunk 1]
```diff
@@ -46,13 +46,10 @@ const Header = function() {
                 Support<span className="HideOnSmallScreen"> the Daily</span>
               </button>
               <select name="amount" className="tsd-select form-control">
-                <option value={5}>$5</option>
-                <option value={10}>$10</option>
-                <option value={25}>$25</option>
                 <option value={50}>$50</option>
-                <option value={100}>$100</option>
-                <option value={500}>$500</option>
```
Comment (epicfaace) [inline src/pages/Header.jsx:54]: Can you set the value of a3 to also be 50 and not 5? (later in this page) (see https://stackoverflow.com/questions/11019954/paypal-recurring-payments-form)

**Review by epicfaace — APPROVED** [review]
